---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: instances
- name: Delete instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    state: absent
  loop: "{{instances.openstack_servers}}"   
