---
# Install HAProxy
- name: install HAProxy
  yum:
    name: "{{ payload }}" 
    state: latest

# Enable HAProxy
- name: enable HAProxy
  service:
    name: "{{ payload }}"
    enabled: yes

#Configure HAProxy
- name: configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart "{{ payload }}"

#Start HAProxy
- name: start HAProxy
  service:
    name: "{{ payload }}"
    state: started
